add_test( [==[Empty arrays have certain properties]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[Empty arrays have certain properties]==])
set_tests_properties( [==[Empty arrays have certain properties]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
add_test( [==[Non-empty arrays have certain properties]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[Non-empty arrays have certain properties]==])
set_tests_properties( [==[Non-empty arrays have certain properties]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
add_test( [==[copying array]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[copying array]==])
set_tests_properties( [==[copying array]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
add_test( [==[swapping array]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[swapping array]==])
set_tests_properties( [==[swapping array]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
add_test( [==[paren operator]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[paren operator]==])
set_tests_properties( [==[paren operator]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
add_test( [==[square bracket operator]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[square bracket operator]==])
set_tests_properties( [==[square bracket operator]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
add_test( [==[paren and square bracket equivalence]==] /home/cameron/home/source/repos/CMakeProject1/test/test/test_array2d [==[paren and square bracket equivalence]==])
set_tests_properties( [==[paren and square bracket equivalence]==] PROPERTIES WORKING_DIRECTORY /home/cameron/home/source/repos/CMakeProject1/test/test)
set( test_array2d_TESTS [==[Empty arrays have certain properties]==] [==[Non-empty arrays have certain properties]==] [==[copying array]==] [==[swapping array]==] [==[paren operator]==] [==[square bracket operator]==] [==[paren and square bracket equivalence]==])
